### ISSUE TITLE
Building Object Field Var_AD / Var_AE

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenLoco/ObjectEditor#27]
https://github.com/OpenLoco/ObjectEditor/blob/606e81fafb57b038a5085c8346f7dabce550f993/Core/Objects/BuildingObject.cs#L103

`Var_AD` is the numAnimationSequences
And `Var_AE` is the animation sequences. It is a list of parts that should be drawn depending on the tick.

**Comment by LeftofZen** [comment]
will update this - i checked all vanilla objects, all of them have var_AD/numAnimationsSequences == 0, so is it unused?

**Comment by duncanspumpkin** [comment]
> will update this - I checked all vanilla objects, all of them have var_AD/numAnimationsSequences == 0, so is it unused? I have var_AE as a list of uint8_t, is that correct? or is the type object_id instead of uint8_t

Try BLDCTY28 it has two elevators that animate.

**Comment by duncanspumpkin** [comment]
also i was slightly incorrect in my description its a list of heights to draw the elevator image at. So kind of only usable for elevators.

**Comment by LeftofZen** [comment]
> Try BLDCTY28 it has two elevators that animate.

ah yep so it does, cheers, will update the variable name
