### ISSUE TITLE
ImageIds for G1.dat are not correct

### ISSUE THREAD

**Issue by LeftofZen** [OpenLoco/ObjectEditor#30]
I've copied the G1 image id names from https://github.com/OpenLoco/OpenLoco/blob/master/src/OpenLoco/src/Graphics/ImageIds.h
and they all line up until 3550 when it appears to go off by 2 places (2 missing title menu lesson sprites) . This can be seen from the exported-and-named files:

![image](https://github.com/OpenLoco/ObjectEditor/assets/7483209/f93f1eff-80a4-4404-9a12-832d91e510c6)

**Comment by duncanspumpkin** [comment]
There is a difference between different versions of the base game perhaps that is what you are seeing
