### ISSUE TITLE
Station Image Error

### ISSUE THREAD

**Issue by glenjimen** [OpenLoco/ObjectEditor#35]
Hey LeftofZen, I've really been enjoying using your tool :-)

I found four station objects from Wisim-Welt that your tool cannot open the images.  Then when I clicked "export to directory" your tool exported the images of the next object up in the main list.  The status window at the bottom just displayed loading object... and saved images to...  no errors
Maybe it needs an error message when it can't find the images.  And it's a bug if it's exporting the wrong images.
Probably the objects are faulty too...  I don't have time tonight to load them up, and edit them into my trackst.dat file

I hope you can make some sense of this ;-)

[station files.zip](https://github.com/OpenLoco/ObjectEditor/files/14305607/station.files.zip)

**Comment by LeftofZen** [comment]
uh-oh, I'll take a look! i definitely need to add the object validation code from openloco so i can detect/display when objects are truly bugged, vs when my tool has the bug.

just to confirm, these 4 objects are all train signals? but i see the problem, i'll debug and fix it today

**Comment by glenjimen** [comment]
Oh that's weird.  Yeah my tool shows them as signals too, even though the sprites are of stations and buildings.
![stationError](https://github.com/OpenLoco/ObjectEditor/assets/51429904/739f1ee6-889b-4b3c-8a03-30d0b22c1f39)
Maybe people were trying to expand the number slots for station buildings before OpenLoco was a thing, by using signal slots.  They all have 4 sprites except for trdepot which has 16.  Regular Loco Tool opens them, which makes sense because that's probably the tool the original creator used.  
I don't see right off how these are buggy, the .xml looks okay.

**Comment by glenjimen** [comment]
Huh, that took me a minute, but they do work in-game.  And trains clip thru them quite goofy.  
![test signals](https://github.com/OpenLoco/ObjectEditor/assets/51429904/b5c6802a-7194-4c98-911d-5d313d6a947b)
It's probably good for your tool to handle objects like this correctly.  This seems like an obsolete way to add station buildings, after OpenLoco added new functionality.

**Comment by LeftofZen** [comment]
Interesting, and you'll be glad to know I've found and fixed the issue, will do a release soon

![image](https://github.com/OpenLoco/ObjectEditor/assets/7483209/9f61297b-4246-474c-9843-655ab0df6557)
