### ISSUE TITLE
User Interface Bugs

### ISSUE THREAD

**Issue by glenjimen** [OpenLoco/ObjectEditor#52]
I found a couple unimportant bugs with the UI, I'll just list them all here

1. If you start playing a long sound file, then navigate to a different object in the index, you cannot stop the original sound playing.  You can start & stop new sound files, but the first one keeps playing until finished even if you navigate back to the object and try to stop it.   I found this while playing SNDFRGHT, 63s long.
2. If you click directly on the expand/collapse arrow in the index display, it will expand/collapse the entries as expected.  But if you click on the group banner, then every-other click works?  It's kinda inconsistent. 
3. The wrong icons for group banners are displayed if you open a directory without one of every object type.  ex:  I've opened a folder with just the Dekosoft BNSF set, it just has Competitor, Sound & Vehicle objects.  They were assigned icons for Airport, Bridge & Buildings respectively.  
4. If you choose a new image background color, it is reset to white when you select an object from a new object group.  ex : color -> black while looking at vehicles, but when you open a bridge object, the color swaps back to white.
Edit : now I'm getting the color reset bug after selecting an object without images, or one that fails to load images?
5.  At first I was unable to open a lot of objects that I know aren't buggy it just showed nothing in the main view.  Then I realized I should hit recreate index, seems to have fixed it.  Maybe show a prompt or message to recreate the index in this case?

**Comment by glenjimen** [comment]
One more
The group header for vehicles shows how many sub-groups it contains, like 6 or fewer.  Like aircraft, bus, ship...  It should probably show the total number of vehicle objects, hundreds to several thousand usually.

**Comment by LeftofZen** [comment]
1. Will fix
2. It isn't every other click - it is double click. This is normal behaviour.
3. I don't get this problem locally. Can you show a screenshot?
4. Yeah I see it happening if you set a colour then click another group. It's because the colour is stored with the objectviewmodel, which is reset (and hence the colour is reset). I can probably cache it and load it when the new viewmodel is loaded
5. Ah yes, that should fix #3

**Comment by glenjimen** [comment]
2. Okay yeah it works correctly, the delay in expanding groups with 1000's of objects threw me off.
3. See attached image.
4. Not necessary to fix.  Each vehicle looks better on a different background.  Maybe default to blue like folks are used to seeing? 
5. After recreating the index, the icons are still assigned incorrectly. 

![objectEditorIconBug](https://github.com/user-attachments/assets/a7dd958e-b228-4852-b278-325049e3b321)

I haven't found any really bad bugs, so far your editor seems quite stable and useful!

**Comment by LeftofZen** [comment]
- the wrong icon is interesting, I can't repro it. I have however redone the icons in an unrelated change yesterday, soi'll be interested to see if this fixes it for you.
- I'll default it to SteelBlue, looks like this:
![image](https://github.com/user-attachments/assets/83886c42-cfe8-4303-b82c-a8f2c84c8b4f)
