### ISSUE TITLE
Show unknown flags

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenLoco/ObjectEditor#64]
It would be useful if it could show flags that are currently unnamed as well. For example i was just looking for information on vehicles that have VehicleObjectFlag::1 set but the editor doesn't show that flag.

**Comment by LeftofZen** [comment]
hmm I'm not sure how to show flags we don't know exist. I could just add an extra field to show the integer value of the flag?

**Comment by duncanspumpkin** [comment]
> what if I just do the latter? it looks like this ![image](https://private-user-images.githubusercontent.com/7483209/359141636-78d3c850-9a0a-48e1-9407-dc5024d4dbe6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwOTM3NzYsIm5iZiI6MTcyNDA5MzQ3NiwicGF0aCI6Ii83NDgzMjA5LzM1OTE0MTYzNi03OGQzYzg1MC05YTBhLTQ4ZTEtOTQwNy1kYzUwMjRkNGRiZTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTlUMTg1MTE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDAzYjRiMTk0Y2UwMDdhZjU1Y2YwNGNlZTJjMWVhN2YyNTQ5ZjM0MDFkYzE1OTRjMmY5ZDc2N2Q4MTEwMzdiOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.O0QiCDtasnbjsBTIetTEVRTYv0wv4J8wPDpDcsxQLGI)

Yup that's what I'd like
