### ISSUE TITLE
Fix Korean and Chinese language encoding problem

### ISSUE THREAD

**Issue by phobos2390** [OpenLoco/ObjectEditor#9]
Korean and Chinese language strings use a particular non utf8 encoding that, when read by the tool are displayed incorrectly. Fixing this would be a good idea

**Comment by LeftofZen** [comment]
I believe I've fixed this by using ISO-8559-1 encoding for the string table reading and writing, which is the same/very similar to the original string encoding (its closer than ASCII, anyways)
